# Generated by Django 4.2.6 on 2023-10-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
